#chatGPT 연결
openai:
  api-key: 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
chatgpt:
  api-key: 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
spring:
  #swagger 설정
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    include: API-KEY #chatGPT api-key
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/course
    username: root
    password: codeypaper0118
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
server:
  port: 9090
  address: localhost